### ISSUE TITLE
cuda runtime error (700) : an illegal memory access was encountered 

### ISSUE THREAD

**Issue by Lauenburg** [EndlessSora/TSIT#17]
I try to test your code with a custom dataset using the following command:

```bash
python train.py \
    --name sis_maps \
    --task SIS \
    --gpu_ids 0,1 \
    --checkpoints_dir  ./checkpoints\
    --batchSize 4 \
    --dataset_mode custom \
    --croot ../../datasets/maps \
    --sroot ../../datasets/maps \
    --nThreads 4 \
    --gan_mode hinge \
    --num_upsampling_layers more \
    --use_vae \
    --alpha 1.0 \
    --display_freq 1000 \
    --save_epoch_freq 20 \
    --niter 100 \
    --niter_decay 100 \
    --lambda_vgg 20 \
    --lambda_feat 10 \
    --no_instance \
    --label_dir ../../datasets/maps/trainA \
    --image_dir ../../datasets/maps/trainB
```

The goal is to translate images from the domain of `trainA` into images from the domain of `trainB`. Do I understand the flags `label_dir` and `image_dir` correctly?

The dataset and network are created without throwing an error:

```bash
dataset [CustomDataset] of size 1096 was created
Network [TSITGenerator] was created. Total number of parameters: 332.4 million. To see the architecture, do print(network).
Network [MultiscaleDiscriminator] was created. Total number of parameters: 5.6 million. To see the architecture, do print(network).
Network [ConvEncoder] was created. Total number of parameters: 10.5 million. To see the architecture, do print(network).
create web directory ./checkpoints/sis_maps/web...
  0%|                                                                                  | 0/200 [00:00<?, ?it/sTHCudaCheck FAIL file=/pytorch/aten/src/THC/generic/THCTensorScatterGather.cu line=384 error=700 : an illegal memory access was encountered
```

However, the code fails when it tries to create a web directory:

```bash
Traceback (most recent call last):
  File "train.py", line 37, in <module>
    trainer.run_generator_one_step(data_i)
  File "/net/coxfs01/srv/export/coxfs01/pfister_lab2/share_root/Lab/leander/tsit/TSIT/trainers/pix2pix_trainer.py", line 30, in run_generator_one_step
    g_losses, generated = self.pix2pix_model(data, mode='generator')
  File "/n/home05/lauenburg/.conda/envs/tsit/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/n/home05/lauenburg/.conda/envs/tsit/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/n/home05/lauenburg/.conda/envs/tsit/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/net/coxfs01/srv/export/coxfs01/pfister_lab2/share_root/Lab/leander/tsit/TSIT/models/pix2pix_model.py", line 37, in forward
    input_semantics, real_image = self.preprocess_input(data)
  File "/net/coxfs01/srv/export/coxfs01/pfister_lab2/share_root/Lab/leander/tsit/TSIT/models/pix2pix_model.py", line 118, in preprocess_input
    input_semantics = input_label.scatter_(1, label_map, 1.0)
RuntimeError: cuda runtime error (700) : an illegal memory access was encountered at /pytorch/aten/src/THC/generic/THCTensorScatterGather.cu:384
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered (insert_events at /pytorch/c10/cuda/CUDACachingAllocator.cpp:771)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x46 (0x2b41150c3536 in /n/home05/lauenburg/.conda/envs/tsit/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0x7ae (0x2b4114e7dfbe in /n/home05/lauenburg/.conda/envs/tsit/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::TensorImpl::release_resources() + 0x4d (0x2b41150b3abd in /n/home05/lauenburg/.conda/envs/tsit/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0x5236b2 (0x2b40c90696b2 in /n/home05/lauenburg/.conda/envs/tsit/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x523756 (0x2b40c9069756 in /n/home05/lauenburg/.conda/envs/tsit/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #20: __libc_start_main + 0xf5 (0x2b40c08cd555 in /lib64/libc.so.6)
```

I tried resolving the issue by following e.g.: 
- https://github.com/pytorch/pytorch/issues/21819
- https://github.com/pytorchbearer/torchbearer/issues/658#issuecomment-581407150
But I could not resolve it.

**Comment by EndlessSora** [comment]
`--task SIS` is only applicable for the semantic image synthesis task, _i.e._, mask -> image. It does some preprocessing with the segmentation label maps with a specific format. Could you please try to use `--task AST`?
P.S. If the dataset is paired like "maps", maybe "SIS" is more suitable. However, you may need to modify the code to discard some preprocessing designed for segmentation label maps.

**Comment by Lauenburg** [comment]
awesome, thank you! The training now worked! However, my slurm job was canceled after 24 hours while the training only reached 89 of 200 epochs. How can I continue the training?
